controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    # Os controladores abaixo DEVEM ter 4 espaços de recuo (dentro de ros__parameters)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

simple_velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
